# Generated by Django 4.2.5 on 2023-10-02 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_profile_pic_alter_user_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_of_creation', models.DateField()),
                ('deadline', models.DateField()),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('attachments', models.ImageField(blank=True, null=True, upload_to='card_attachments/')),
                ('assignee', models.ManyToManyField(related_name='assigned_cards', to=settings.AUTH_USER_MODEL)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lists')),
            ],
        ),
    ]
