# Generated by Django 4.2.5 on 2023-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
